### Задание 1

In [11]:
import numpy as np

In [20]:
a = np.array([
    [1,6],
    [2,8],
    [3,11],
    [3,10],
    [1,7]
])

In [22]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2

In [23]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [30]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1] # или a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1])

8.0

In [34]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

### Задание 4

In [35]:
a_t = a.T
a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [37]:
ts_4 = np.cov(a_t)
ts_4

array([[1. , 2. ],
       [2. , 4.3]])